name: Stability Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Flat CLI
      uses: actions/checkout@master
      with:
        repository: FlatLang/Flat
        path: Flat

    - name: Checkout Flat JS Writer
      uses: actions/checkout@master
      with:
        repository: FlatLang/Flat-js
        path: Flat-JS

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build CLI
      run: |
        mvn -f Flat install

    - name: Build JS Writer
      run: |
        mvn -f Flat-JS install

    - name: Checkout Standard library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Standard-Library
        path: Standard-Library

    - name: Checkout Nest library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Nest
        path: Nest

    - name: Checkout Compiler-String-Extensions library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Compiler-String-Extensions
        path: Compiler-String-Extensions

    - name: Checkout Network library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Network
        path: Network

    - name: Checkout MySQL library
      uses: actions/checkout@master
      with:
        repository: FlatLang/MySQL
        path: MySQL

    - name: Checkout Redis library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Redis
        path: Redis

    - name: Checkout Svg library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Svg
        path: Svg

    - name: Checkout Stability-Test library
      uses: actions/checkout@master
      with:
        repository: FlatLang/Stability-Test
        path: Stability-Test

    - name: Download Airship
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'FlatLang/Airship'
        version: 'tags/v0.1.0-alpha'
        file: 'index.js'
        target: 'airship.js'

    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Build Stability Test with Airship
      env:
        FLAT_HOME: ..
      working-directory: Stability-Test
      run: |
        node ../airship.js install

    - name: Build Stability Test
      run: |
        java -jar Flat/target/flatc.jar \
          example Stability-Test/src \
          -l Nest \
          -l Compiler-String-Extensions \
          -l Network \
          -l MySQL \
          -l Redis \
          -l Svg \
          -install-dir . \
          -main stabilitytest/StabilityTest \
          -o example/bin/ExecutableJS \
          -target js

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ExecutableJS.js
        path: example/bin/ExecutableJS.js

    - name: Run Stability Test
      run: |
        node example/bin/ExecutableJS.js
